name: Ubuntu-sanitizers

on:
  schedule:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
    # * is a special character in YAML so you have to quote this string
    # every Sunday at 2 am
    - cron:  '0 2 * * SUN'

jobs:
  build-ubuntu-sanitizers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: ["-fsanitize=address", "-fsanitize=leak", "-fsanitize=thread", "-fsanitize=undefined"]

    steps:
    # https://github.com/marketplace/actions/cancel-workflow-action
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print system information
      run: lscpu

    - name: Print OS information
      run: lsb_release -a

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libdc1394-22-dev libv4l-dev liblapack-dev libopenblas-dev libeigen3-dev

    - name: Clone visp-images
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      # https://remarkablemark.org/blog/2022/09/25/check-git-branch-exists-in-remote-repository/
      run: |
        git ls-remote --exit-code --heads https://github.com/${{ github.actor }}/visp-images.git ${BRANCH_NAME} >/dev/null 2>&1
        EXIT_CODE=$?
        if [[ $EXIT_CODE == '0' ]]; then
          git clone --depth 1 --branch ${BRANCH_NAME} https://github.com/${{ github.actor }}/visp-images ${HOME}/visp-images
        else
          git clone --depth 1 https://github.com/lagadic/visp-images ${HOME}/visp-images
        fi
        echo "VISP_INPUT_IMAGE_PATH=$HOME" >> $GITHUB_ENV
        echo ${VISP_INPUT_IMAGE_PATH}

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_C_FLAGS=${{ matrix.flags }} -DCMAKE_CXX_FLAGS=${{ matrix.flags }} -DCMAKE_LDFLAGS=${{ matrix.flags }} -DCMAKE_BUILD_TYPE=Debug
        cat ViSP-third-party.txt

    - name: Compile
      working-directory: build
      run: make -j$(nproc)

    - name: Run unit tests with sanitizers
      working-directory: build
      run: ctest -j$(nproc) --output-on-failure
