name: Windows - clang
on:
  pull_request:
    types: [opened, reopened, synchronize]

# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre#comment133398800_72408109
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        name: [windows-latest-clang]

        include:
          - name: windows-latest-clang
            os: windows-2022
            compiler: clang-cl

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Display the workspace path
      working-directory: ${{ github.workspace }}
      run: pwd

    - name: Clone visp-images
      shell: bash
      # https://remarkablemark.org/blog/2022/09/25/check-git-branch-exists-in-remote-repository/
      run: |
        git clone --depth 1 https://github.com/lagadic/visp-images ${HOME}/visp-images
        echo "VISP_INPUT_IMAGE_PATH=$HOME/visp-images" >> $GITHUB_ENV
        echo "VISP_INPUT_IMAGE_PATH: ${{ env.VISP_INPUT_IMAGE_PATH }}"

    - name: Configure ViSP
      working-directory: ${{ github.workspace }}
      run: |
        set VISP_INPUT_IMAGE_PATH=${{ env.VISP_INPUT_IMAGE_PATH }}
        echo "VISP_INPUT_IMAGE_PATH: "
        echo %VISP_INPUT_IMAGE_PATH%
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -T "ClangCl" -A "x64"
        type ViSP-third-party.txt
        pwd

    - name: Build ViSP
      working-directory: ${{ github.workspace }}\build
      run: |
        pwd
        cmake --build . --config Release

    - name: Install ViSP
      working-directory: ${{ github.workspace }}\build
      run: |
        cmake --build . --config Release --target install

    - name: Check installation folder
      working-directory: ${{ github.workspace }}\build
      run: |
        dir ${{ github.workspace }}\build\install\
        dir ${{ github.workspace }}\build\install\x64\
        dir ${{ github.workspace }}\build\install\x64\vc17\
        dir ${{ github.workspace }}\build\install\x64\vc17\bin

    - name: Test ViSP
      working-directory: ${{ github.workspace }}\build
      run: |
        set VISP_INPUT_IMAGE_PATH=${{ env.VISP_INPUT_IMAGE_PATH }}
        echo "VISP_INPUT_IMAGE_PATH: "
        echo %VISP_INPUT_IMAGE_PATH%
        set PATH=%PATH%;${{ github.workspace }}\build\install\x64\vc17\bin
        echo "PATH: "
        echo %PATH%
        ctest --output-on-failure -C Release -V
